version: "3"
services:
  # web:
  #     restart: always
  #     container_name: web
  #     ports:
  #         - '2020:80'
  #     image: 'wisehackermonkey/website:latest'
  #     labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.web.rule=Path(`/`)"
  
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/web`)"
      
  businesscardpuzzle:
      container_name: businesscardpuzzle
      # env_file: 
        # - .env
      image: wisehackermonkey/businesscardpuzzle:latest
      environment:
        NODE_ENV: production
      ports:
        - 3333:3000
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.businesscardpuzzle.rule=Path(`/puzzle`)"
        
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # - "--api.insecure=true"
      # - "--providers.docker=false"
      # - "--providers.docker.exposedbydefault=true"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.businesscardpuzzle.address=:3333"
      # - "--entrypoints.website.address=:2020"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock