version: '3.3'
services:
    website:
        restart: always
        container_name: website
        ports:
            - '80:80'
            - '443:80'
        image: 'wisehackermonkey/website:react'
